Implements a complete batch-download of selected files
ffont/freesound-explorer pull request #71
Opened 2018-08-09 12:47 UTC by noVaSon

Highlights:
• add download Button to SoundInfoModal
• submit freesound-ids to the flask backend
• download the files and the metadata there and put it in a zip archive
• send it back to the frontend and save to disk
• remove the temporary files downloaded from the server with a delayed cleanup Thread

Adresses #38

2018-08-09 13:09 UTC, noVaSon commented
Some notes to myself:

• csv should be optimized (only selected columns, reshape lists (now: [u'tag1, u'tag2']))
• filenames should be identical with the entry in the csv
• parts of the python implementation should be modularized

2018-08-10 05:50 UTC, ffont commented
Wow, this looks like big news!
I'll be away for a week approx so I won't be able to review. I'll have a look after that.
In this way you also have time to add further improvements if needed.
Thanks!

2018-08-10 13:32 UTC, noVaSon commented
Thank you for this note @ffont!

Seems like we had similar temperatures this summer (37°C in Berlin this week!) :)
Enjoy your vacation!!

2018-08-13 13:41 UTC, noVaSon commented
Ok, ready for a merge :D

2018-08-20 07:19 UTC, ffont commented on backend/fszipper.py
> +from backend.settings import DOWNLOAD_TEMP
`DOWNLOAD_TEMP` need to be added in `settings.example.py`.

2018-08-20 07:38 UTC, ffont requested changes
Great work! Here are some comments:

- If not logged in, download fails with 500 error (unauthorized). Maybe this could be prevented by not allowing to download if user not logged in.
- I'd use the same download icon as in the sound panel as it is easier to understand (IMO).
- Also the download icon should disappear when no sounds are selected. 
- I'd add a badge with the number of selected sounds on top of the icon so things become even clearer.
- Building the CSV sometimes fails when trying to download sounds with non ascii characters in their description or name. For example downloading this one fails: https://freesound.org/people/sijeh/sounds/394561/
- Also maybe there is no need to add that much data in the CSV. Could be something simpler like the file we add when a pack is downloaded in Freesound (mainly license/user info)

2018-08-20 07:38 UTC, ffont commented on backend/fszipper.py
> +from backend.settings import DOWNLOAD_TEMP
And maybe rename it to `DOWNLOAD_FOLDER_PATH` for consistency with other settings.

2018-08-20 07:38 UTC, ffont commented on src/containers/Sidebar/actions.js
> +    dispatch(displaySystemMessage(`Prepare download of ${selectedSounds.length} Sounds, please wait...`, MESSAGE_STATUS.INFO));
"Preparing download of..." better than "Prepare download of..."

2018-08-22 14:03 UTC, noVaSon commented
News:

I adressed your issues @ffont  - exept the unicode problem creating the .csv
I'll take care of this the next few days.

Best!
Eric

2018-08-23 10:44 UTC, noVaSon reviewed
Helpful suggestions! Than you!
It is ready to merge and deploy now.

2018-08-23 11:29 UTC, ffont commented
Hi,
I tried it again, it works almost perfect now, but still I have a couple of comments:

- When not logged in, the download still fails. If clicking on download with the user not being logged in we should show a message that this action requires login.
- When selecting multiple sounds (shit + click) I would prevent the info window from opening (for the sound being currently selected). This is not really part of this PR but I realized it while trying it for downloading sounds and to me it makes sense. Basically the idea is that when a sound is selected we show the info window unless shit key is pressed (does this make sense to you?).
- I'd only show the download option when more than 1 sound is selected. Otherwise there is already a download button in the info window of the selected sound. We prefer users to use that method because they'll download directly from Freesound instead of Freesound Explorer downloading from Freesound and then serving to users.
- You'll have to add instructions about the download feature in the README.

Thanks for the work, it's a really nice feature!

2018-08-23 14:00 UTC, noVaSon commented
@ffont 

I did it!
Much better now, you are right!

Can you please tell me how to access githubusercontent for uploading pictures though?

2018-08-23 15:34 UTC, ffont commented
> Can you please tell me how to access githubusercontent for uploading pictures though?

Hah, I think I played a trick which is to upload an image by dragging it into an issue or PR comment (here!) and then copying the URL. Just trying it now again:

![364911_s_a33eb96f_freesoundbeastwhoosh](https://user-images.githubusercontent.com/478615/44535588-a54b2400-a6fa-11e8-844e-e44a64876e82.jpg)

You drag an image in this editor and Github uploads it and creates a URL than then I used in the readme. Then I guess I deleted the comments. Hacky!

2018-08-28 09:51 UTC, noVaSon commented
@ffont > Thanks for the hacky trick 🍡 
I'm DonE!

2018-08-28 14:36 UTC, ffont approved these changes

2018-08-28 14:37 UTC, merged